### ISSUE TITLE
only table view has auto-number

### ISSUE THREAD

**Issue by ayugioh2003** [ayugioh2003/notion-table-auto-number#2]
board view dont need auto-number

```css
@-moz-document domain("notion.so") {
.notion-table-view .notion-collection_view-block {
  list-style-type: none;
  counter-reset: css-counter 0; /* initializes counter to 0; use -1 for zero-based numbering */
}

.notion-table-view .notion-collection-item {
  counter-increment: css-counter 1; /* Increase the counter by 1. */
  transform: translateX(-2rem);
}

.notion-table-view .notion-collection-item:before {
  content: counter(css-counter, decimal-leading-zero) ". | "; /* Apply counter before children's content. */
  color: brown;
  width: 2rem;
}
}
```
